apiVersion: cloudscheduler.googleapis.com/v1
kind: Job
metadata:
  name: malloy-slack-bot-keep-alive
spec:
  description: "Keep Malloy Slack Bot alive by pinging health endpoint every 5 minutes"
  schedule: "*/5 * * * *"  # Every 5 minutes
  timeZone: "UTC"
  
  httpTarget:
    uri: "https://malloy-slack-bot-234201753528.us-central1.run.app/ping"
    httpMethod: GET
    headers:
      User-Agent: "Cloud-Scheduler-Keep-Alive/1.0"
    
  retryConfig:
    retryCount: 3
    maxRetryDuration: "60s"
    minBackoffDuration: "5s"
    maxBackoffDuration: "30s"
    maxDoublings: 3 