apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: malloy-slack-bot
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/jss89-coursera/malloy-slack-bot:latest
        ports:
        - name: http1
          containerPort: 8080  # Health check port
        env:
        - name: MCP_URL
          value: "https://malloy-mcp-server-fixed-234201753528.us-central1.run.app/mcp"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-bot-token
              key: latest
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-app-token
              key: latest
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        - name: VERTEX_PROJECT_ID
          value: "jss89-coursera"
        - name: VERTEX_LOCATION
          value: "us-central1"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45  # Slightly longer for Python startup
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 30 